FROM node:16-alpine

WORKDIR /home/node/app

RUN apk add --no-cache   bash   git   curl

RUN npm install @nestjs/cli

COPY package.json .

RUN npm install

COPY . .

ENTRYPOINT [ "npm", "run", "start:dev" ]

USER node

EXPOSE 300